name: Auto-Update IPA from Nightly

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download latest IPA zip
        run: |
          curl -L -o sulfur.zip https://nightly.link/Seeike/Sora/workflows/build/dev/Sulfur-IPA.zip

      - name: Unzip the IPA
        run: |
          rm -rf tmp-ipa
          mkdir -p tmp-ipa
          unzip -o sulfur.zip -d tmp-ipa
          mkdir -p public-build
          cp tmp-ipa/Sulfur.ipa public-build/Sulfur.ipa

      - name: Update metadata via script
        run: |
          node scripts/update-metadata.js

      - name: Commit & push if changed
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@example.com"
          git add -f public-build/Sulfur.ipa sorarepo.json
          git diff --quiet && git diff --staged --quiet \
            || git commit -m "Auto: Update IPA and metadata [skip ci]"
          git push
